In [13]:
import numpy as np
import math 


In [14]:
#we will be using the CRR, risk neutral method for pricing the option, european option
#we define the stock price at each and every stage to have 2 values,                             
#if S_0 is the price at a particular level, then the two prices are given by u*S_0 and d*S_0, u>d
#and u*d = 1
# u is given by e^(v*sqrt(t)) where, v is the underlying volatility and t the time interval
#the probability of each upward move is given by p =(e^(r*dt)-d)/(u-d), where r is the annual risk free rate and e = 2.7124


In [15]:
def OptionsVal(n, S, K, r, v, T, PC):  # n: no of periods(single period or multi period, etc)in the pricing,
                                       #  S: current stock price, K: strike price, r:risk free interest rate,
                                       #  v: underlying volatility, T:period of valuation, PC: 0 for call option, 1 for put option
    dt = T/n                #time interval for each and every level up
    
    u = m.exp(v*m.sqrt(dt))  
    d = 1/u                  #initializing u and d and also the risk neutral probability p 
    p = (m.exp(r*dt)-d)/(u-d)
    
    
    Stock_tree = np.zeros((n+1, n+1))  # initializing array
                               # for price of the stock and 
                               # corresponding value of the option   
    Cm = np.zeros((n+1, n+1))
    
   
    
#building the stock price tree as a 2-D array such that any element C[i,j] gives rise to 2 elements, C[i,j+1] and C[i+1,j+1]
                              
           
    for i in range(n+1):
        for j in range(n+1):
            if i<=j:
                Stock_tree[i,j] = S*math.pow(u,j-2*i)
  
 #option pricing tree
    for j in range(n+1, 0, -1):
        for i in range(j):
            if (PC == 1):     #put option                          
                if(j == n+1):
                    Cm[i,j-1] = max(K-Stock_tree[i,j-1], 0)     
                else:
                    Cm[i,j-1] = m.exp(-r*dt) * (p*Cm[i,j] + (1-p)*Cm[i+1,j]) 
            if (PC == 0):     #call option                  
                if (j == n + 1):
                    Cm[i,j-1] = max(Stock_tree[i,j-1]-K, 0)     
                else:
                    Cm[i,j-1] = m.exp(-r*dt) * (p*Cm[i,j] + (1-p)*Cm[i+1,j])  
    return [Stock_tree,Cm] 




In [16]:
S = 100
k = 100
r = .05
v = .3

T = 20/36
n = 10
PC =0
Stock_tree,Cm = OptionsVal(n,S,k,r,v,T,PC)
print('Pricing:\n',np.matrix(Stock_tree.astype(int)))
print('Option Values:\n',np.matrix(Cm.astype(int)))

Pricing:
 [[100 107 115 123 132 142 152 164 176 188 202]
 [  0  93 100 107 115 123 132 142 152 164 176]
 [  0   0  86  93 100 107 115 123 132 142 152]
 [  0   0   0  80  86  93 100 107 115 123 132]
 [  0   0   0   0  75  80  86  93 100 107 115]
 [  0   0   0   0   0  70  75  80  86  93 100]
 [  0   0   0   0   0   0  65  70  75  80  86]
 [  0   0   0   0   0   0   0  60  65  70  75]
 [  0   0   0   0   0   0   0   0  56  60  65]
 [  0   0   0   0   0   0   0   0   0  52  56]
 [  0   0   0   0   0   0   0   0   0   0  49]]
Option Values:
 [[  9  14  19  26  34  43  53  64  76  89 102]
 [  0   5   8  12  18  25  33  43  53  64  76]
 [  0   0   2   4   7  11  17  24  33  42  52]
 [  0   0   0   1   1   3   5   9  15  23  32]
 [  0   0   0   0   0   0   0   1   3   7  15]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0

In [ ]:
#in order to find the option price, we must select a certain volatility according to the market,
#the price of the stock, and the risk-free interest rate(bonds,treasuries), then accordingly,
#putting in the no of periods and time-duration to expiry, one can calculate the option price,
#which is the first element of Cm